Name:           ros-indigo-designator-integration-lisp
Version:        0.0.3
Release:        0%{?dist}
Summary:        ROS designator_integration_lisp package

Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-alexandria
Requires:       ros-indigo-cl-tf2
Requires:       ros-indigo-designator-integration-msgs
Requires:       ros-indigo-roslisp
BuildRequires:  ros-indigo-alexandria
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-cl-tf2
BuildRequires:  ros-indigo-designator-integration-msgs
BuildRequires:  ros-indigo-roslisp

%description
Integration of Designator Communication via ROS as Lisp interface

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Fri Dec 04 2015 Jan Winkler <winkler@cs.uni-bremen.de> - 0.0.3-0
- Autogenerated by Bloom

